### ISSUE TITLE
Feature Request / Pickeball Simulation

### ISSUE THREAD

**Issue by djm30** [philipandwaffle/particle_sim#1]
Particle simulation is cool, but can you make it so its a pickeball instead, that would be cooler I think

**Comment by philipandwaffle** [comment]
This is implemented in the current master branch and took a lot of work for a shitty joke. 

When I read this feature request It remined of the famous quote by Rick Sanchez from the hit tv show "Rick and Morty"

[[Rick Sanchez]] Come on, flip the ball, djm30, you're not gonna regret it. The payoff is huge. I turned myself into a pickle ball, djm30! Boom! Big reveal! I'm a pickle ball! What do you think about that? I turned myself into a pickle ball! W-w-what are you just staring at me for, bro, I turned myself into a pickle ball, djm30.

[[djm30]]: And?

[[Rick Sanchez]]: And? What more do you want tacked on to this? I turned myself into a pickle ball and 9/11 was an inside job?

[[djm30]]: Was it?

[[Rick Sanchez]]: Who cares, djm30? Global acts of terrorism happen every day. Uh, here's something that's never happened before... I'M A PICKLE BALL! I'm pickle siiiiiim!

**Comment by djm30** [comment]
Thank you for going above and beyond on this issue, I am glad to see our fantastic sport being represented in such amazing simulations!
